version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
