name: Portal Client CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 18.19
        uses: actions/setup-node@v4
        with:
          node-version: 18.19
      - name: Install Dependencies
        run: npm i
      - name: EsLint Check
        run: npm run lint
      - name: Prettier Check
        run: npm run format:check
      - name: Run Test
        run: npm test
